services:
  db:
    image: postgres:15
    container_name: sushitime-database
    environment:
      POSTGRES_PASSWORD: "12345r"
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5505:5432"
      - "5432"
  server:
    build: ./server
    container_name: sushitime-server
    ports:
      - '5506:5506'
    expose:
      - "5506"
    depends_on:
      - db
    working_dir: /app
    command: npm run dev
    volumes:
      - ./server:/app
      - /server/node_modules
  client:
    build: ./client
    container_name: sushitime-client
    depends_on:
      - server
    ports:
      - "5507:5173"
    working_dir: /app
    command: npm run dev
    volumes:
      - .client:/app
      - /server/node_modules

volumes:
  pgdata:
    name: sushitimedb_pgdata
