services:
  postgres:
    image: postgres:15
    container_name: sushitime-postgres
    environment:
      POSTGRES_PASSWORD: "12345r"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5505:5432"

volumes:
  pgdata:
    name: sushitimedb_pgdata
