\c sushitimedb postgres
INSERT INTO products(title, description, price, weight) VALUES ('California Classic Rolls', 'Rice, nori, cheese, crab, avocado, mosago orange. 8 pieces', 35, 230);
INSERT INTO products(title, description, price, weight) VALUES ('California Salmon Rolls', 'Rice, nori, cheese, salmon, avocado, mosago red. 8 pieces', 35, 230);
INSERT INTO products(title, description, price, weight) VALUES ('California Eel Rolls', 'Rice, nori, cheese, eel, avocado, mosago black, sesame seeds. 8 pieces', 35, 230);
INSERT INTO products(title, description, price, weight) VALUES ('Canada Classic Rolls', 'Rice, nori, cream cheese, avocado, eel. 8 pieces', 40, 240);
INSERT INTO products(title, description, price, weight) VALUES ('Canada Rolls with Salmon', 'Rice, nori, cream cheese, avocado, salmon, ell. 8 pieces', 45, 240);
INSERT INTO products(title, description, price, weight) VALUES ('Canada Rolls with Shrimp', 'Rice, nori, cream cheese, avocado, shrimp, ell. 8 pieces', 45, 240);
INSERT INTO products(title, description, price, weight) VALUES ('Philadelphia Rolls with Shrimp', 'Rice, nori, cream cheese, cucumber, shrimp. 8 pieces', 35, 265);
INSERT INTO products(title, description, price, weight) VALUES ('Philadelphia Light Rolls', 'Rice, nori, cream cheese, cucumber, salmon. 8 pieces', 30, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Philadelphia Classic Rolls', 'Rice, nori, cream cheese, cucumber, salmon. 8 pieces', 35, 265);
INSERT INTO products(title, description, price, weight) VALUES ('Philadelphia Rolls with Crab', 'Rice, nori, cream cheese, cucumber, crab stick, salmon. 8 pieces', 35, 265);
INSERT INTO products(title, description, price, weight) VALUES ('Philadelphia Rolls with Eel', 'Rice, nori, cream cheese, cucumber, eel, salmon. 8 pieces', 40, 265);
INSERT INTO products(title, description, price, weight) VALUES ('Tuna Rolls', 'Rice, cheese, avocado, tuna. 8 pieces', 40, 250);
INSERT INTO products(title, description, price, weight) VALUES ('Pyramid Rolls', 'Rice, cheese, cucumber, eel, salmon, tuna. 8 pieces', 40, 260);
INSERT INTO products(title, description, price, weight) VALUES ('Mizuri Rolls', 'Rice, cheese, tomago, crab, masago orange, avocado. 8 pieces', 35, 230);
INSERT INTO products(title, description, price, weight) VALUES ('Tori spicy Rolls', 'Rice, nori, chicken, cucumber, hot sauce, tomato, sesame seeds. 8 pieces', 30, 240);
INSERT INTO products(title, description, price, weight) VALUES ('Osaka Rolls', 'Rice, cream cheese, cucumber, eel obr, sesame seeds mix. 8 pieces', 35, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Salmon spicy Rolls', 'Rice, nori, spicy sauce, cucumber, salmon, sesame seeds. 8 pieces', 30, 235);
INSERT INTO products(title, description, price, weight) VALUES ('Snow Crab Rolls', 'Rice, cream cheese, crab, salmon caviar. 8 pieces', 35, 230);
INSERT INTO products(title, description, price, weight) VALUES ('Alaska Rolls', 'Rice, cream cheese, cucumber, salmon, white sesame seeds. 8 pieces', 30, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Bonito Rolls with Smoked Salmon', 'Rice, nori, tomago, cucumber, smoked salmon, shavings of tune. 8 pieces', 40, 250);
INSERT INTO products(title, description, price, weight) VALUES ('Bonito Rolls with Chicken', 'Rice, nori, chicken, cucumber, spicy sauce. 8 pieces', 35, 215);
INSERT INTO products(title, description, price, weight) VALUES ('Carolina Rolls', 'Rice, nori, cheese, smoked salmon, tobiko. 8 pieces', 40, 285);
INSERT INTO products(title, description, price, weight) VALUES ('White Sesame Rolls', 'Rice, nori, crab, avocado, cucumber, sesame seeds. 8 pieces', 30, 230);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Salmon', 'Rice, nori, salmon. 6 pieces', 15, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Crab', 'Rice, nori, crab stick. 6 pieces', 15, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Chicken', 'Rice, nori, chicken. 6 pieces', 15, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Smoked Salmon', 'Rice, nori, smoked salmon. 6 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Cucumber', 'Rice, nori, cucumber. 6 pieces', 15, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Eel', 'Rice, nori, eel. 6 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Tuna', 'Rice, nori, tuna. 6 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Shrimp', 'Rice, nori, shrimp. 6 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Avocado', 'Rice, nori, avocado. 6 pieces', 15, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Tobiko', 'Rice, nori, tobiko. 6 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Maki Rolls with Tomago', 'Rice, nori, tomago. 6 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Salmon Rolls', 'Rice, nori, cheese, salmon, avocado, tobiko orange. 6 pieces', 35, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Eel Rolls', 'Rice, nori, cheese, eel, avocado, tobiko red. 6 pieces', 35, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Shrimp Rolls', 'Rice, nori, cheese, shrimp, avocado, tobiko black. 6 pieces', 30, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Tuna Rolls', 'Rice, nori, cheese, tuna, avocado, tobiko orange. 6 pieces', 35, 220);
INSERT INTO products(title, description, price, weight) VALUES ('Vegetable Rolls', 'Rice, nori, cucumber, avocado, pepper, salad, tomato. 6 pieces', 25, 185);
INSERT INTO products(title, description, price, weight) VALUES ('Lirra Rolls', 'Rice, nori, cheese, cucumber, shrimp, salmon, tobiko. 8 pieces', 35, 240);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Salmon Rolls', 'Rice, nori, cheese, tomago, cucumber, tobiko, salmon, cheese sauce. 8 pieces', 40, 310);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Eel Rolls', 'Rice, nori, cheese, tomago, cucumber, eel, cheese sauce. 8 pieces', 40, 275);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Tuna Rolls', 'Rice, nori, cheese, tomago, cucumber, tuna, cheese sauce. 8 pieces', 40, 275);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Crab Rolls', 'Rice, nori, cheese, tomago, cucumber, tobiko, crab stick, cheese sauce. 8 pieces', 35, 305);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Chicken Rolls', 'Rice, nori, cheese, tomago, cucumber, chicken, cheese sauce, sesame seeds. 8 pieces', 35, 295);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Shrimp Rolls', 'Rice, nori, cheese, tomago, cucumber, shrimp, cheese sauce. 8 pieces', 35, 275);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Spicy Salmon Rolls', 'Rice, nori, cheese, cucumber, salmon, salad, spicy sauce. 8 pieces', 40, 285);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Spicy Eel Rolls', 'Rice, nori, cheese, cucumber, eel, spicy sauce, sesame seeds. 8 pieces', 40, 270);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Spicy Tuna Rolls', 'Rice, nori, cheese, cucumber, tuna, salad, spicy sauce. 8 pieces', 40, 285);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Spicy Crab Rolls', 'Rice, nori, cheese, cucumber, crab stick, salad, spicy sauce. 8 pieces', 35, 285);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Spicy Chicken Rolls', 'Rice, nori, cheese, cucumber, chicken, salad, spicy sauce, white and black sesame. 8 pieces', 35, 295);
INSERT INTO products(title, description, price, weight) VALUES ('Baked Spicy Shrimp Rolls', 'Rice, nori, cheese, cucumber, shrimp, salad, cheese spicy sauce. 8 pieces', 35, 285);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Spicy Eby Rolls', 'Rice, nori, cheese, avocado, shrimp, spicy sauce, tobiko red. 8 pieces', 40, 255);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Crab Rolls', 'Rice, nori, cheese, avocado, crab, tobiko orange. 8 pieces', 35, 260);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Chicken Rolls', 'Rice, nori, cheese, cucumber, chicken. 8 pieces', 35, 245);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Salmon Rolls', 'Rice, nori, cheese, cucumber, salmon. 8 pieces', 40, 245);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Eel Rolls', 'Rice, nori, cheese, avocado, eel, sesame seed. 8 pieces', 45, 250);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Tuna Rolls', 'Rice, nori, cheese, cucumber, tuna, tobiko. 8 pieces', 45, 260);
INSERT INTO products(title, description, price, weight) VALUES ('Tempura Shrimp Rolls', 'Rice, nori, cheese, cucumber, shrimp, tobiko red. 8 pieces', 40, 235);
INSERT INTO products(title, description, price, weight) VALUES ('Salmon Sushi', 'Rice, nori, salmon. 2 pieces', 20, 80);
INSERT INTO products(title, description, price, weight) VALUES ('Tuna Sushi', 'Rice, nori, tuna. 2 pieces', 20, 80);
INSERT INTO products(title, description, price, weight) VALUES ('Shrimp Sushi', 'Rice, nori, shrimp. 2 pieces', 20, 80);
INSERT INTO products(title, description, price, weight) VALUES ('Eel Sushi', 'Rice, nori, eel. 2 pieces', 25, 80);
INSERT INTO products(title, description, price, weight) VALUES ('Avocado Sushi', 'Rice, nori, avocado. 2 pieces', 15, 80);
INSERT INTO products(title, description, price, weight) VALUES ('Gunkan Chuka', 'Rice, nori, chuka. 2 pieces', 20, 120);
INSERT INTO products(title, description, price, weight) VALUES ('Nigiri Salmon', 'Rice, fresh salmon. 2 pieces', 25, 100);
INSERT INTO products(title, description, price, weight) VALUES ('Nigiri Tuna', 'Rice, fresh tuna. 2 pieces', 28, 100);
INSERT INTO products(title, description, price, weight) VALUES ('Sashimi Mix', 'Salmon, tuna, seabass. 9 pieces', 50, 150);
INSERT INTO products(title, description, price, weight) VALUES ('Unagi Nigiri', 'Rice, grilled eel, unagi sauce. 2 pieces', 30, 110);
INSERT INTO products(title, description, price, weight) VALUES ('Tamago Nigiri', 'Rice, sweet Japanese omelet. 2 pieces', 18, 90);
INSERT INTO products(title, description, price, weight) VALUES ('Margherita', 'Tomato sauce, mozzarella, basil. 30 cm', 25, 450);
INSERT INTO products(title, description, price, weight) VALUES ('Pepperoni', 'Tomato sauce, mozzarella, pepperoni. 30 cm', 30, 500);
INSERT INTO products(title, description, price, weight) VALUES ('Hawaiian', 'Tomato sauce, mozzarella, ham, pineapple. 30 cm', 32, 480);
INSERT INTO products(title, description, price, weight) VALUES ('Quattro Formaggi', 'Cream sauce, mozzarella, gorgonzola, parmesan, ricotta. 30 cm', 35, 520);
INSERT INTO products(title, description, price, weight) VALUES ('BBQ Chicken', 'BBQ sauce, mozzarella, chicken, red onion, cilantro. 30 cm', 34, 510);
INSERT INTO products(title, description, price, weight) VALUES ('Edamame', 'Steamed soybeans with salt. 1 portion', 12, 150);
INSERT INTO products(title, description, price, weight) VALUES ('Chicken Wings', 'Crispy fried chicken wings with BBQ sauce. 6 pieces', 22, 300);
INSERT INTO products(title, description, price, weight) VALUES ('Spring Rolls', 'Fried rolls with vegetables and chicken. 4 pieces', 18, 200);
INSERT INTO products(title, description, price, weight) VALUES ('French Fries', 'Crispy fries with ketchup. 1 portion', 15, 250);
INSERT INTO products(title, description, price, weight) VALUES ('Garlic Bread', 'Toasted bread with garlic butter. 4 pieces', 14, 180);
INSERT INTO products(title, description, price, weight) VALUES ('Caesar', 'Romaine lettuce, croutons, parmesan, Caesar dressing', 28, 300);
INSERT INTO products(title, description, price, weight) VALUES ('Greek Salad', 'Cucumber, tomato, olives, feta cheese, olive oil', 26, 320);
INSERT INTO products(title, description, price, weight) VALUES ('Seafood Salad', 'Shrimp, squid, mussels, greens, lemon dressing', 35, 280);
INSERT INTO products(title, description, price, weight) VALUES ('Caprese', 'Tomato, mozzarella, basil, balsamic glaze', 24, 250);
INSERT INTO products(title, description, price, weight) VALUES ('Avocado Salad', 'Avocado, cherry tomatoes, arugula, lemon dressing', 30, 270);
INSERT INTO products(title, description, price, weight) VALUES ('Cola', 'Carbonated soft drink. 0.5L', 5, 500);
INSERT INTO products(title, description, price, weight) VALUES ('Green Tea', 'Japanese green tea. 0.3L', 8, 300);
INSERT INTO products(title, description, price, weight) VALUES ('Orange Juice', 'Freshly squeezed orange juice. 0.3L', 10, 300);
INSERT INTO products(title, description, price, weight) VALUES ('Mineral Water', 'Still mineral water. 0.5L', 4, 500);
INSERT INTO products(title, description, price, weight) VALUES ('Mojito (Non-Alc)', 'Lime, mint, soda. 0.4L', 12, 400);
INSERT INTO products(title, description, price, weight) VALUES ('Miso Soup', 'Tofu, seaweed, miso paste. 1 portion', 15, 300);
INSERT INTO products(title, description, price, weight) VALUES ('Tom Yum', 'Shrimp, mushrooms, lemongrass, chili. 1 portion', 25, 350);
INSERT INTO products(title, description, price, weight) VALUES ('Chicken Noodle', 'Chicken broth, noodles, vegetables. 1 portion', 20, 400);
INSERT INTO products(title, description, price, weight) VALUES ('Pumpkin Soup', 'Creamy pumpkin soup with croutons. 1 portion', 18, 350);
INSERT INTO products(title, description, price, weight) VALUES ('Borscht', 'Beetroot soup with sour cream. 1 portion', 22, 380);
